### PR TITLE
[NLU-3216]Resolved spanish word 'barra' for time 

### PR DESCRIPTION
**Pull request by CiaraCrowe**
Resolved Spanish word 'barra' for date entity type

### CODE REVIEW

**Comment by CiaraCrowe** [comment]
tests passing: https://jenkins.ininica.com/view/Dialog%20Engine/job/NLU/job/Recognizers-Text/

**Comment by CiaraCrowe** [comment]
Tests passing; https://jenkins.ininica.com/view/Dialog%20Engine/job/NLU/job/Recognizers-Text/484/

**Review by colm-dillon — APPROVED** [review]

**Review by andrew-gradinari — APPROVED** [review]

**Review by KanchanKumar12 — APPROVED** [review]

**Review by kevinwalshgen — APPROVED** [review]

**Review by BobbyMartins5 — APPROVED** [review]
NIT: For future PR's, put more description into the title, such as language and specific entity type

**Comment by CiaraCrowe** [comment]
https://jenkins.ininica.com/view/Dialog%20Engine/job/NLU/job/Recognizers-Text/485/ updated tests

**Pull request merged**
