### PR TITLE
[bugfix/NLU-3071] Fix incorrect recognition of large number expressed as a fraction 

### PR DESCRIPTION
**Pull request by rbrennangen**
Large numbers expressed as fractions are not resolving correctly for PT, FR, DE and IT.

Problem is already fixed in EN and ES and in .NET for all languages (https://github.com/microsoft/Recognizers-Text/pull/2810).

**Notes:**

- Update parsers for DE, PT, IT and FR to match (as close as possible) to EN/ES implementations.
- Update tests to use new functionality.

**Examples:**

**Input:** trois milliards et demi 

**Expected Output:** 3500000000

**Actual:** 1500000000

**Input:** sei milioni e mezzo 

**Expected Output:** 6500000

**Actual:** 3000000

### CODE REVIEW

**Comment by colm-dillon** [comment]
LGTM - One thing to be careful of is the fact that this might fix an issue also seen in .NET which could prompt MSFT to ask us to also fix there if we attempt to merge this into their repo.

**Review by colm-dillon — APPROVED** [review]

**Comment by sanhal** [comment]
Same here, could you checj if any tests need to be enabled for python now?

**Comment by kevinwalshgen** [comment]
Will the changes that you've made to the resources files not get overridden by the `resource-generator` when it pulls in updates from the pattern files?

**Comment by rbrennangen** [comment]
> Will the changes that you've made to the resources files not get overridden by the `resource-generator` when it pulls in updates from the pattern files?

@kevinwalshgen Do you mean the changes to `english_date_time.py`? This commit is a direct result of pulling in updates from the pattern files. I believe it is from a change in .NET (or other) that hasn't been pulled into Python yet.

**Review by Conor-Keaney — APPROVED** [review]

**Review by samhickey25 — APPROVED** [review]

**Review by srandal — APPROVED** [review]

**Pull request merged**
