### PR TITLE
[Bugfix/NLU-3061] "3 y medio" is resolved incorrectly

### PR DESCRIPTION
**Pull request by rbrennangen**
**Issue:**
Not resolving “3 y medio“ (three and a half) correctly in ES.
It is resolved as two separate entities - “3” and “0.5” instead of “3.5”

This fix represents a small drift from MS .NET implementation i.e. .NET is unable to handle cases of number input where it is digit+"and a half".

### CODE REVIEW

**Review by Conor-Keaney — APPROVED** [review]

**Comment by colm-dillon** [comment]
LGTM - One thing to be careful of is the fact that this might fix an issue also seen in .NET which could prompt MSFT to ask us to also fix there if we attempt to merge this into their repo.

**Review by colm-dillon — APPROVED** [review]

**Comment by sanhal** [comment]
@rbrennangen , could you check if there are any test which need to to be updated?

**Comment by samhickey25** [comment]
Is it worth drifting from MS over this fix?

**Comment by rbrennangen** [comment]
> Is it worth drifting from MS over this fix?

Gonna bring this up in the PL later.

**Pull request closed without merging**
